sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake

install:
  - make -s V=1
  - make -s V=1 install

script:
  - make -s V=1 test
